# Generated by Django 2.1.7 on 2019-03-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog', '0001_initial'),
        ('users', '0004_auto_20190302_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='UserCreation',
        ),
    ]
