# Generated by Django 2.1.7 on 2019-03-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190307_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
