# Generated by Django 2.1.7 on 2019-03-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auditentry_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditEntry',
        ),
    ]
