# Generated by Django 2.1.7 on 2019-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('usuario', models.CharField(max_length=256, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
